from typing import Sequence, Protocol
from uuid import UUID

from app.core.repository import BaseRepository
from .models import User

class AbstractUserRepository(Protocol):
    def get_by_id(self, record_id: UUID, include_deleted: bool = False) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_all(self, limit: int, offset: int, include_deleted: bool = False) -> Sequence[User]: ...
    def create(self, data: dict) -> User: ...
    def update(self, instance: User, data: dict) -> User: ...
    def soft_delete(self, instance: User) -> User: ...
    def hard_delete(self, instance: User) -> None: ...


class UserRepository(BaseRepository[User]):
    def __init__(self, session) -> None:
        super().__init__(User, session)

    def get_by_email(self, email: str) -> User | None:
        return self.get_by_field("email", email)