"""add set null on expense category fk

Revision ID: 273050d29e48
Revises: a012ffd3bef2
Create Date: 2026-05-24 14:18:47.486360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273050d29e48'
down_revision: Union[str, None] = 'a012ffd3bef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'expenses', ['id'])
    op.drop_constraint('expenses_category_id_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_category_id_fkey', 'expenses', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'expenses', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
