"""fix category unique constraint per user

Revision ID: a8148dde9e88
Revises: 273050d29e48
Create Date: 2026-05-31 21:14:49.406186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8148dde9e88'
down_revision: Union[str, None] = '273050d29e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_unique_constraint('uq_category_name_user', 'categories', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_name_user', 'categories', type_='unique')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
