"""add new indexes to expenses table

Revision ID: e57b6462fa14
Revises: a8148dde9e88
Create Date: 2026-06-06 19:15:05.519615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57b6462fa14'
down_revision: Union[str, None] = 'a8148dde9e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_categories_user_id', 'categories', ['user_id'], unique=False)
    op.create_index('idx_expenses_category_id', 'expenses', ['category_id'], unique=False)
    op.create_index('idx_expenses_user_date', 'expenses', ['user_id', 'date'], unique=False)
    op.create_index('idx_expenses_user_date_active', 'expenses', ['user_id', 'date'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expenses_user_date_active', table_name='expenses', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('idx_expenses_user_date', table_name='expenses')
    op.drop_index('idx_expenses_category_id', table_name='expenses')
    op.drop_index('idx_categories_user_id', table_name='categories')
    # ### end Alembic commands ###
